"""Render a `Documentation` as a single Markdown document.

The output is plain CommonMark with GFM tables — readable on GitHub, by
Obsidian/Typora, and convertible to PDF via pandoc. No template engine is
involved; the implementation is a straight concatenation so the file is
trivial to extend (extra columns, custom sections) without learning a
template DSL.
"""

from __future__ import annotations

from unwind.docs.ir import ColumnDoc, Documentation, ModelDoc


def render_markdown(doc: Documentation) -> str:
    """Return the full Markdown rendering of `doc`."""
    parts: list[str] = ["# Project documentation", ""]
    parts.append(f"_{len(doc.models)} models. Generated by unwind._")
    parts.append("")
    if doc.models:
        parts.append("## Table of contents")
        parts.append("")
        for name in doc.models:
            parts.append(f"- [{name}](#{_anchor(name)})")
        parts.append("")

    for model_doc in doc.models.values():
        parts.extend(_render_model(model_doc))
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def _render_model(model: ModelDoc) -> list[str]:
    lines: list[str] = [f"## {model.name}", ""]
    if model.description:
        lines.append(model.description)
        lines.append("")

    meta = [
        ("Group", model.group or "—"),
        ("Tags", ", ".join(model.tags) if model.tags else "—"),
        ("Materialized", model.materialized),
        ("Kind", model.kind),
        ("Upstreams", _link_list(model.upstreams)),
        ("Downstreams", _link_list(model.downstreams)),
    ]
    for label, value in meta:
        lines.append(f"- **{label}:** {value}")
    lines.append("")

    if model.columns:
        lines.append("### Columns")
        lines.append("")
        lines.append("| Column | Type | Description | Inherited from |")
        lines.append("| --- | --- | --- | --- |")
        for column in model.columns:
            lines.append(_render_column_row(column))
        lines.append("")

    if model.annotations:
        lines.append("### Annotations")
        lines.append("")
        for note in model.annotations:
            lines.append(f"- Line {note.line}: {note.text}")
        lines.append("")

    if model.rendered_sql:
        lines.append("### SQL")
        lines.append("")
        lines.append("```sql")
        lines.append(model.rendered_sql.rstrip())
        lines.append("```")

    return lines


def _render_column_row(column: ColumnDoc) -> str:
    description = column.description or "—"
    inherited = column.inherited_from or "—"
    type_str = column.type or "—"
    cells = [column.name, type_str, _md_escape(description), _md_escape(inherited)]
    if column.stats is not None:
        # Stats append a couple of columns when present. Keep the canonical
        # 4-column table for compatibility and put stats in a sub-line.
        cells[2] = (
            f"{cells[2]}<br>_(rows={column.stats.row_count}, "
            f"nulls={column.stats.null_count}, "
            f"distinct={column.stats.distinct_count})_"
        )
    return "| " + " | ".join(cells) + " |"


def _link_list(names: tuple[str, ...]) -> str:
    if not names:
        return "—"
    return ", ".join(f"[{n}](#{_anchor(n)})" for n in names)


def _anchor(name: str) -> str:
    return name.lower().replace("_", "-").replace(" ", "-")


def _md_escape(text: str) -> str:
    """Escape pipe characters and collapse newlines for safe table cells."""
    return text.replace("|", "\\|").replace("\n", " ")
